### ISSUE TITLE
core.tunnel.exceptions.ResponseError: Php runtime error

### ISSUE THREAD

**Issue by mmomasters** [nil0x42/phpsploit#81] opened 2019-02-09 16:35 UTC
[#] CMD('ls'): Running...
[-] Server response coudn't be unparsed (maybe invalid PASSKEY ?)
[-] ls: Python runtime error (exception occured):
[#] Traceback (most recent call last):
[#]   File "/home/phpsploit/plugins/file_system/ls/plugin.py", line 76, in <module>
[#]     response = lister.send()
[#]   File "/home/phpsploit/src/api/server/payload.py", line 29, in send
[#]     result = tunnel.send(php_vars + self.payload)
[#]   File "/home/phpsploit/src/core/tunnel/__init__.py", line 85, in send
[#]     request.open(raw_payload)
[#]   File "/home/phpsploit/src/core/tunnel/handler.py", line 603, in open
[#]     raise ResponseError(self.errmsg_response)
[#] core.tunnel.exceptions.ResponseError: Php runtime error
[!] Response Error: Php runtime error
[#] CMD('ls'): Returned 1

Sometimes it works, sometimes not, I tryed on multiple servers and I also tryed to change this values but without any difference (running on latest Kali Linux 2019.1)

REQ_DEFAULT_METHOD
REQ_MAX_HEADERS
REQ_MAX_HEADER_SIZE

**Comment by nil0x42** [comment] 2019-02-10 18:39
If you tried to settle REQ_* settings with lower values and it still doesn't work all the time, it can be due to 2 things:
If there is some load balancer (or if you use multiple TARGETs `help set TARGET`), then a server might accept your payload as valid, while the other doesn't.

To identify the problem, i need some informations:
- does this also happens with other plugins ? which ones fail, and which ones work orectly ?
- do you use default values for BACKDOOR and REQ_HEADER_PAYLOAD ?
- does `ls` plugin only fails while listing specific directories ? dos this happens only for very large directories ?
- does the php runtime error also prints the php errors ?
- what version of phpsploit do you use ? (commit-id or release tag)

Thank you for your feedback, i hope to resolve this issue ASAP, and i'm investigating but couldn't reproduce from now, so your help is very welcome.

**Comment by mmomasters** [comment] 2019-02-11 14:34
This is very weird as all is back to normal now and all is working, maybe an VPN issue... You can close the issue as I can't reproduce this error.

**Comment by nil0x42** [comment] 2019-02-12 22:24
Okay, closing from now.
Feel free to re-open if you encounter this issue again.

Thank you

**Closed by nil0x42** 2019-02-12 22:24 UTC
Labels: bug, couldn't reproduce
